name: Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract release version
        id: get_version
        run: MOD_VERSION=${GITHUB_REF#refs/tags/v}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # This is needed to be able to run ./gradlew below
      # You can run `git update-index --chmod +x gradlew` then remove this step.
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          MOD_VERSION: ${{ steps.get_version.outputs.version }}
          
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/surgeofkhroma-${{ steps.get_version.outputs.version }}.jar
          asset_name: surgeofkhroma-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive